### ISSUE TITLE
[statiq-data] @Inject named JsonObject from data dir

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-statiq#15]
Watched files (json and yaml) in `src/main/resources/data` (configurable)
=> Injectable as JsonObject (vert.x) with file name as name

**Comment by ia3andy** [comment]
@melloware or @mcruzdev ?

**Comment by melloware** [comment]
So just so I am clear on the requirement we need to:

- [ ] Walk the configurable directory `src/main/resources/data` for `json, yaml, yml` extensions
- [ ] Load them as `JsonObject` (what about the Yaml as Yaml is not JSON?)
- [ ] Make those newly created objects Injectable by adding them to the BeanManager

**Comment by mcruzdev** [comment]
If you want @melloware, I can get this one.

**Comment by mcruzdev** [comment]
Is there a need to think about live reload?

**Comment by ia3andy** [comment]
> Is there a need to think about live reload?

for now we can do live-reload with restart, but you will need to put the data in the live reload context
and reload on file change or config change.
